version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/storedb
    restart: unless-stopped
    volumes:
          - ./backend/app/barcodes:/app/barcodes

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backup:
    build: ./backup
    depends_on:
      - db
    volumes:
      - ./respaldos:/backups
      - ~/.config/rclone:/root/.config/rclone  # Monta configuración rclone desde Mac al contenedor
    environment:
      - PGPASSWORD=pass  # Contraseña del usuario Postgres


volumes:
  pgdata:
